CREATE TABLE Libros (
	id INT  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 ,INCREMENT BY 1),
    isbn VARCHAR(32),
    nombre VARCHAR(32),
	precio DECIMAL(10,2),
    cantidad INT);

CREATE TABLE Usuario (
	id INT  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 ,INCREMENT BY 1),
	nombre VARCHAR(32),
	apellido VARCHAR(32),
	domicilio VARCHAR(32),
	saldo DECIMAL(10,2),
	numTarjeta VARCHAR(32),
	puntajeCrediticio INT);
	
CREATE TABLE Factura (
	id INT  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 ,INCREMENT BY 1),
	montoTotal DECIMAL(10,2),
	fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	numTarjeta VARCHAR(32),
	mesesSinIntereses INT);
	
CREATE TABLE Envio (
	id INT  NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 ,INCREMENT BY 1),
	idFactura INT,
	nombrePaqueteria VARCHAR(32),
	diasAEntrega INT);
	 
	
	
	
