<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSEntregasWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSEntregasWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSEntregasWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsentregas/">
    <import location="http://localhost:8080/WAEntregas/WSEntregas?WSDL" namespace="http://wsentregas/"/>
    <plnk:partnerLinkType name="WSEntregasLinkType">
        <plnk:role name="WSEntregasRole" portType="ns:WSEntregas"/>
    </plnk:partnerLinkType>
</definitions>
